### ISSUE TITLE
Smart Gateway fails to connect to AMQP due to changes in SGO:latest image

### ISSUE THREAD

**Issue by pleimer** [redhat-service-assurance/telemetry-framework#44]
`The` latest updates in the smart gateway operator image change the address that smart gateway looks for the amqp1 bus on the cluster. This causes the smart gateway pod to error out when deploying SAF with the 'quickstart.sh' script on a fresh minishift.

With the most recent image of smart-gateway operator, smart gateway is looking for the amqp1 bus at the host service address amqp://messaging-internal-white.sa-telemetry.svc:5672/collectd/telemetry

However, the amqp1 bus is exposed at amqp://qdr-white.sa-telemetry.svc:5672/collectd/telemetry

**Steps to Reproduce**
All existing images and image streams should be deleted from the minishift vm:
```
$ minishift start
$ minishift ssh
$ docker images | grep 172.30.1.1:5000 | awk '{print $3}' | xargs docker image rmi 
$ exit
$ eval $(minishift oc-env)
$ oc remove is --all
$ git pull https://github.com/redhat-service-assurance/telemetry-framework.git
$ cd telemetry-framework/deploy
$ ./quickstart.sh
```

**Diagnosis**
```
$ oc get pods

NAME                                      READY     STATUS    RESTARTS   AGE
alertmanager-sa-0                         2/2       Running   0          30s
prometheus-operator-1-vxlmp               1/1       Running   0          44s
prometheus-white-0                        3/3       Running   1          29s
qdr-operator-5985987f84-qhtx8             1/1       Running   0          46s
qdr-white-6fb67d46d6-cxzzp                1/1       Running   0          2s
smart-gateway-operator-68b64478f6-pkz92   1/1       Running   0          40s
white-smartgateway-1-ckhn9                0/1       Error     1          18s

```

```
$ oc logs white-smartgateway-<unique tag>

2019/07/30 20:00:38 Metric server at : 0.0.0.0:8081
2019/07/30 20:00:40 HTTP server is ready....
2019/07/30 20:00:40 Connecting to AMQP1 : amqp://messaging-internal-white.sa-telemetry.svc:5672/collectd/telemetry
2019/07/30 20:00:40 Listening.....
2019/07/30 20:00:40 AMQP Dial tcp dial tcp: lookup messaging-internal-white.sa-telemetry.svc on 172.30.0.2:53: no such host
2019/07/30 20:00:40 Could not connect to Qpid-dispatch router. is it running? : dial tcp: lookup messaging-internal-white.sa-telemetry.svc on 172.30.0.2:53: no such host
```

**Comments and Work-Around**
Currently, my work around is to use an earlier version of the SGO image. When running ./quickstart.sh with upstream, I change the line in import-upstream.sh from:

``
oc import-image smart-gateway-operator:latest --from=quay.io/redhat-service-assurance/smart-gateway-operator:latest --confirm
``

to:
``
oc import-image smart-gateway-operator:latest --from=quay.io/redhat-service-assurance/smart-gateway-operator:last-known-compatible-with-sgo-1.0-3 --confirm
``

**Comment by leifmadsen** [comment]
I think I know the issue. On the latest version of the SGO it now uses the `amqp_url` and the default configuration for the `SmartGateway` object in the `telemetry-framework` repo is to use the old `amqmetrics_url` parameter.

If you just update the `./deploy/service-assurance/smartgateway/smartgateway.yaml` file and `s/amqpmetric_url/amqp_url` I think it'll work again for you.

Don't close this issue out yet because I need to make some other changes to `telemetry-framework` and this is one of the changes I can make.
